services:
  ms-factura:
    build: .
    ports:
      - "8082:8082"
    environment:
      SERVER_PORT: 8082
      KAFKA_BOOTSTRAP_SERVERS: broker:9092
      KAFKA_CONSUMER_GROUP_ID: ms-factura-group
      KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      KAFKA_CONSUMER_KEY_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      KAFKA_CONSUMER_VALUE_DESERIALIZER: org.apache.kafka.common.serialization.StringDeserializer
      FOODTECH_KAFKA_TOPIC: foodtech.factura.created
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: kelvin.vargas@sofka.com.co
      SPRING_MAIL_PASSWORD: chhr xglv okfg xjdl
      NOTIFICATION_ENABLED: "true"
      NOTIFICATION_CHANNEL: email
      NOTIFICATION_SUBJECT_TEMPLATE: "Factura generada {invoiceRef}"
      NOTIFICATION_BODY_TEMPLATE: "Factura {invoiceRef} generada en fecha {date} para cliente {customer}."
      FOODTECH_RABBITMQ_EXCHANGE: foodtech.exchange
      FOODTECH_RABBITMQ_QUEUE: foodtech.queue
      FOODTECH_RABBITMQ_ROUTINGKEY: foodtech.routingkey
    networks: [foodtech-net]

networks:
  foodtech-net:
    external: true
    name: foodtech-net