spring.application.name=ms-factura
server.port=${SERVER_PORT:8082}
# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:ms-factura-group}
spring.kafka.consumer.auto-offset-reset=${KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
spring.kafka.consumer.key-deserializer=${KAFKA_CONSUMER_KEY_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}
spring.kafka.consumer.value-deserializer=${KAFKA_CONSUMER_VALUE_DESERIALIZER:org.apache.kafka.common.serialization.StringDeserializer}

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
foodtech.rabbitmq.exchange=${FOODTECH_RABBITMQ_EXCHANGE:foodtech.exchange}
foodtech.rabbitmq.queue=${FOODTECH_RABBITMQ_QUEUE:foodtech.queue}
foodtech.rabbitmq.routingkey=${FOODTECH_RABBITMQ_ROUTINGKEY:foodtech.routingkey}

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:kelvin.vargas@sofka.com.co}
spring.mail.password=${SPRING_MAIL_PASSWORD:chhr xglv okfg xjdl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.enabled=${NOTIFICATION_ENABLED:true}
notification.channel=${NOTIFICATION_CHANNEL:email}
notification.email.from=${spring.mail.username}
notification.email.subject-template=${NOTIFICATION_SUBJECT_TEMPLATE:Factura generada {invoiceRef}}
notification.email.body-template=${NOTIFICATION_BODY_TEMPLATE:Factura {invoiceRef} generada en fecha {date} para cliente {customer}.}
foodtech.kafka.topic=${FOODTECH_KAFKA_TOPIC:foodtech.factura.created}