spring.application.name=ms-factura
server.port=8082
# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=ms-factura-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
foodtech.rabbitmq.exchange=foodtech.exchange
foodtech.rabbitmq.queue=foodtech.queue
foodtech.rabbitmq.routingkey=foodtech.routingkey

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:kelvin.vargas@sofka.com.co}
spring.mail.password=${SPRING_MAIL_PASSWORD:chhr xglv okfg xjdl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.enabled=${NOTIFICATION_ENABLED:true}
notification.channel=${NOTIFICATION_CHANNEL:email}
notification.email.from=${NOTIFICATION_EMAIL_FROM:${spring.mail.username}}
notification.email.subject-template=${NOTIFICATION_SUBJECT_TEMPLATE:Factura generada {invoiceRef}}
notification.email.body-template=${NOTIFICATION_BODY_TEMPLATE:Factura {invoiceRef} generada en fecha {date} para cliente {customer}.}